# Generated by Django 2.2.5 on 2020-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200530_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='aboutme',
            field=models.TextField(blank=True),
        ),
    ]
